sudo: required
dist: trusty
language: c
install:
  - sudo apt-get -qq update
  - sudo apt-get install git gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev ccache libgl1-mesa-dev libxml2-utils xsltproc unzip bc python-markdown

script:
  - git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9
  - export PATH=$(pwd)/aarch64-linux-android-4.9/bin:$PATH && export ARCH=arm64 && export CROSS_COMPILE=aarch64-linux-android- && make bullhead_defconfig && make
